Wb1.1.5.0
AMatutat/pmdungeon pull request #36
Opened 2021-05-10 19:17 UTC by AMatutat

*HUD*
- hud can now be toggled between pixel and grid system with `HUD.usePixelSystem(boolean)` (maybe you have to rescale your HUD-Elements for this).

*DungeonCamera*
- dungeon camera do not focus anymore on `(0,0,0)` if no followable object is set. This allows free camera movements. 
- add `DungeonCamera.setFocusPoint(Point)`. Stops following and set the camera on a fix position

*Bug fixes* 
- fixed issue where firstFrame was called twice if you resize the window in `setup`. This would call `setup` again and loads the first level twice.

2021-05-11 06:46 UTC, cagix requested changes
kannst du bitte in der ide nochmal das projekt formatieren?

2021-05-11 06:46 UTC, cagix commented on core/src/de/fhbielefeld/pmdungeon/vorgaben/graphic/HUD.java
> +    private boolean usePixelSystem=false;
please run some formatter 😎 sometimes you use `type = var;`, some other times you use `type=var;`

2021-05-11 11:17 UTC, AMatutat commented on core/src/de/fhbielefeld/pmdungeon/vorgaben/graphic/HUD.java
> +    private boolean usePixelSystem=false;
This is for SQ-Project purposes ^^
i should stop doing these things at night.

2021-05-11 11:31 UTC, AMatutat commented
Hmm, didn't expect ij to format the `readme.md`, have to take a look on that.

2021-05-11 11:33 UTC, AMatutat commented on README.md
> +        List<Texture> idle=new ArrayList<>();
so here we do `var=value` but in the real code not..... interessting behavior

2021-05-11 11:33 UTC, AMatutat commented on README.md
> +lang: de-DE ...
@cagix is this okay?

2021-05-11 11:35 UTC, AMatutat commented on README.md
> +        }
just no.... dont do that

2021-05-11 11:35 UTC, AMatutat commented on README.md
> +        }
arghhhh

2021-05-11 11:36 UTC, AMatutat commented on README.md
> +        if(levelController.checkForTrigger(hero.getPosition())){
again, in real code its `if (blablala)` with a space

2021-05-11 11:37 UTC, AMatutat commented on README.md
> +        return new Point(0.5f, 4.5f);
but why?

2021-05-11 11:37 UTC, AMatutat commented on README.md
> +        bumSound.play();
guess we have some space left?

2021-05-11 11:38 UTC, AMatutat commented on README.md
> +    int levelCounter = 0;
okay........ guess we take this random sh***

2021-05-11 12:34 UTC, cagix commented
wtf, ij is really gready 🤮

2021-05-11 12:34 UTC, cagix commented on README.md
> +        List<Texture> idle=new ArrayList<>();
nice 😂

2021-05-11 12:35 UTC, cagix commented on README.md
> +lang: de-DE ...
this is just a marker for pandoc

2021-05-11 13:02 UTC, AMatutat commented on README.md
> +    int levelCounter = 0;
> yeah, just revert the changes to readme.md (git checkout -- Readme.md)...

can i realy do that AFTER I pushed? 

> is there a switch to exclude this file when formatting the project?

i hope so

2021-05-11 13:38 UTC, cagix commented
> after push

well, you *could* revert the change locally and force push the new head to github … 




> On 11. May 2021, at 15:02, Andre Matutat ***@***.***> wrote:
> 
> 
> @AMatutat commented on this pull request.
> 
> In README.md:
> 
> >  
>  Im unteren Beispiel wird ein Text implementiert, welcher das aktuelle Level ausgibt.
>  
>  ```java
>  public class MyMain extends MainController {
>      .....
>      Label levelLabel;
> -    int levelCounter=0;
> +    int levelCounter = 0;
> 
> yeah, just revert the changes to readme.md (git checkout -- Readme.md)...
> 
> can i realy do that AFTER I pushed?
> 
> is there a switch to exclude this file when formatting the project?
> 
> i hope so
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

2021-05-12 05:51 UTC, cagix commented
> undo ij changes (I know this way is dirty but its also fast) 

if you squash-merge non of this will be visible anymore 😎

2021-05-12 11:51 UTC, AMatutat commented
This should be the last major patch for some time.

2021-05-12 19:55 UTC, merged