Maven Build Skript erstellt
AMatutat/pmdungeon pull request #39
Opened 2021-06-04 05:08 UTC by CrappyAlgorithm

Wir haben die Build Skripte für Maven erstellt.
Diese bieten zudem die Funktion mit dem Target package direkt eine .jar mit allen Abhängigkeiten zu erstellen.
Die Gradle Unterstützung haben wir zur Kompatibilität noch im Projekt gelassen.

Man könnte zusätzlich noch ein Target anlegen, um die Artefakte direkt in das Maven Central Repository zu veröffentlichen, allerdings müsste man dann noch wegen Lizenzen und anderer Kleinigkeiten schauen.
Eine Übersicht zu den Anforderung kann man hier finden:
https://central.sonatype.org/publish/requirements/

2021-06-04 06:41 UTC, cagix commented
duplicate of #38?

2021-06-04 06:50 UTC, CrappyAlgorithm commented
It is not a duplicate, but very similar to #38.
I saw this just after I had already opened it.
I left it open so you can decide which version you prefer.

2021-06-04 09:59 UTC, cagix requested changes
I like this pull request. 

@AMatutat Maybe we should pick the best things from both (#38 and #39)?

2021-06-04 09:59 UTC, cagix commented on core/pom.xml
> +        <jdk.version>14</jdk.version>
shouldn't this be "11"?

2021-06-04 09:59 UTC, cagix commented on core/pom.xml
> +            <groupId>com.google.code.gson</groupId>
like this using properties. however, i'd prefer to sort the dependencies using `groupID`...

2021-06-04 09:59 UTC, cagix commented on core/pom.xml
> +        </plugins>
Isn't a definition for creating a jar file still missing here? I always thought that the core project was the main component of the jar file?

Shouldn't there also be definitions for the execution of (possible) test cases (i.e. `maven-surefire-plugin`, `org.junit.jupiter`,...)?

2021-06-04 09:59 UTC, cagix commented on desktop/pom.xml
> +            <artifactId>core</artifactId>
Does this mean that the `core` sub-project needs to be available on Maven Central?

2021-06-04 09:59 UTC, cagix commented on pom.xml
> +</project>
The properties, dependencies and plug-in definition are duplicated in `core` and `desktop`. Is there a way to define shared things here and inherit them in the subproject POMs?

2021-06-04 10:10 UTC, CrappyAlgorithm commented on core/pom.xml
> +        </plugins>
Maven creates a jar without packed dependencys by default. The modul desktop will create a jar with an without all dependencys.

Yes the test dependencies still need to be added. for testing.

2021-06-04 10:13 UTC, CrappyAlgorithm commented on desktop/pom.xml
> +            <artifactId>core</artifactId>
No, on compile it will be added to the local maven repository and can be used in the second module.

2021-06-04 10:20 UTC, CrappyAlgorithm commented on pom.xml
> +</project>
I had tried to push the properties into the parent pom file, however it then stopped building. I can look there again.

With the dependencys I thought that at first, but those are different libGDX modules in core and desktop.

For the plugins I have already read that you can define them at least partially in the parent pom. I will have a look at that.

2021-06-04 10:26 UTC, CrappyAlgorithm commented on core/pom.xml
> +        <jdk.version>14</jdk.version>
I simply took version 14. But I just tested it with version 11 and it works fine too.

2021-06-04 10:27 UTC, cagix commented on desktop/pom.xml
> +            <artifactId>core</artifactId>
ah, ic :)

2021-06-04 10:29 UTC, cagix commented on core/pom.xml
> +        </plugins>
> Maven creates a jar without packed dependencys by default. The modul desktop will create a jar with an without all dependencys.

ah, okay. i had seen the definition in `desktop` and was wondering if it shouldn't be here too.

2021-06-04 10:35 UTC, CrappyAlgorithm commented on core/pom.xml
> +        <jdk.version>14</jdk.version>
Changed jdk version to 11.

2021-06-04 10:37 UTC, cagix commented on pom.xml
> +</project>
> I had tried to push the properties into the parent pom file, however it then stopped building. I can look there again.

can't really say that i like maven even a little bit :/

> With the dependencys I thought that at first, but those are different libGDX modules in core and desktop.

ah, you're right. hmmmm. nevertheless, they are related and the separation into several files itches somehow. like an itch in a place where you can't scratch ;)

@AMatutat  that would be another strong reason to merge the projects ... ;)

> For the plugins I have already read that you can define them at least partially in the parent pom. I will have a look at that.

👍

2021-06-04 10:38 UTC, CrappyAlgorithm commented on core/pom.xml
> +            <groupId>com.google.code.gson</groupId>
That's a good point. I have now sorted them.

2021-06-04 10:41 UTC, cagix commented on core/pom.xml
> +        <jdk.version>14</jdk.version>
> I simply took version 14. But I just tested it with version 11 and it works fine too.

yeah, that's is the jdk version that the students will be working with. so, we should avoid using a newer jdk here.

2021-06-04 11:33 UTC, CrappyAlgorithm commented on pom.xml
> +</project>
Two individual projects would only make sense if you had a third one like android. Then it would be smart to have the core separately.

I have now successfully placed the properties and plugin configuration into the parent pom.

Unfortunately maven does not like it when the module version in the head uses properties. So I left that out.
![grafik](https://user-images.githubusercontent.com/46276501/120794991-30f36f80-c539-11eb-8a82-c4889c84a7a5.png)

2021-06-04 11:38 UTC, cagix commented on pom.xml
> +</project>
> Two individual projects would only make sense if you had a third one like android. Then it would be smart to have the core separately.

yeah, that's what @AMatutat is considering ... however, looking at the intended purpose of this project, i.e. to use it as library in education, that's probably never going to happen ...

2021-06-04 15:18 UTC, AMatutat commented on pom.xml
> +</project>
>  that's probably never going to happen ...

never say never

2021-06-04 15:32 UTC, Alizame commented on pom.xml
> +</project>
I am on @AMatutat's side here, I think it's better to separate the platform independent core code and the platform dependent code because its future-proof (and in my opinion more elegant) and I don't really see an advantage of merging this? 

I mean, it already works fine, so why even bother?

2021-06-04 16:29 UTC, cagix commented on pom.xml
> +</project>
the separation, even if it appears elegant and future-proof, does add a certain complexity that does not seem justified to me at the moment (and for the foreseeable future). next year, when we have students work directly with this repo as a default, this could`^W`will become another possible source of potential problems.

on the other hand, i don't have to maintain the repo at the moment, so @AMatutat 's vote is the decisive one just now :)

2021-06-09 16:10 UTC, AMatutat commented
> I like this pull request.
> @AMatutat Maybe we should pick the best things from both (#38 and #39)?

Agree. #41

2021-06-09 23:07 UTC, AMatutat commented
#38 and #39 will be combined (we pick the best from each one)

2021-06-09 23:07 UTC, merged