Update gradle
AMatutat/pmdungeon pull request #51
Opened 2021-06-09 14:47 UTC by RipDip

fixes #33 and #43

2021-06-09 16:06 UTC, AMatutat commented
- HUD Implementation looks good to me, can you update the `readme.md` introduction for this? 
- can we keep all PRs clean? 1 Issue = 1PR?

2021-06-09 16:24 UTC, RipDip commented
- I can update the `readme.md` with the same example.
- I could try to spilt the Issues, and then make a new pull request for an issue.

2021-06-09 17:11 UTC, RipDip commented
That should be only Refactoring Packages now

2021-06-09 17:15 UTC, cagix commented
> can we keep all PRs clean? 1 Issue = 1PR?

@AMatutat Seems to me, that @RipDip used  #48 as starting point, so you're seeing quite a lot changes. Once #48 will be merged, this PR (#51) should just have commits 5a31520 and 2c10f28 ... I.e. we have now unfortunately introduced a dependency for merging: first #48 needs to be merged, then (after rebasing) #51 can be merged ...

2021-06-09 18:29 UTC, AMatutat approved these changes
LGTM

2021-06-09 18:29 UTC, AMatutat commented on .gitattributes
> +
we will use #54

2021-06-09 18:36 UTC, AMatutat requested changes
oh yeah, and don't forget the readme ^^

2021-06-12 17:23 UTC, cagix commented on .gitattributes
> +
@RipDip @AMatutat this will vanish once we have merged #48 and rebased this branch/pr ...

2021-06-12 17:36 UTC, cagix requested changes

2021-06-12 17:36 UTC, cagix commented on core/src/de/pmdungeon/graphic/HUD.java
> +<<<<<<< HEAD:core/src/de/pmdungeon/graphic/HUD.java
@RipDip It seems that there was an unresolved Git conflict and you accidentally committed it (including conflict markers)?

2021-06-12 17:45 UTC, cagix requested changes
please fix the committed conflict markers ...

2021-06-13 09:04 UTC, cagix commented
@Tobias321 @RipDip are you working in the same repo?

2021-06-13 09:07 UTC, cagix approved these changes
lgtm :)

ps: however, i only looked at the files in the pr and did not check whether you had actually refactored all the source files.

2021-06-13 09:41 UTC, Tobias321 commented
> @Tobias321 @RipDip are you working in the same repo?

@cagix i had supported @RipDip a little bit in this PR, so we worked on the same repo. he has added me as collaborator.

2021-06-13 11:06 UTC, cagix commented
> > @Tobias321 @RipDip are you working in the same repo?
> 
> @cagix i had supported @RipDip a little bit in this PR, so we worked on the same repo. he has added me as collaborator.

ah, that explains it. i was a bit confused why you could add the pr from @RipDip  :)

2021-06-14 18:26 UTC, cagix commented
> Merge branch 'master' into update_gradle

@RipDip Please, never ever merge `master` into feature branches! This is considered an anti pattern: it yields a horrible history, also rebasing onto master becomes nearly impossible ...

2021-06-14 18:49 UTC, RipDip commented
I only remove the wrong lines for the merge conflict with github

2021-06-14 20:22 UTC, merged

2021-06-15 05:34 UTC, cagix commented
@RipDip @AMatutat when we merge `master` into our feature branches and afterwards the feature branches back into `master`, we create nasty loops in the history. thats hard to read / understand and also complicates things ... that's an anti pattern for a reason, so please do **rebase** your feature branches to get the current content of `master`, do not merge the master into your feature! 

<img width="1002" alt="Screenshot 2021-06-15 at 07 26 32" src="https://user-images.githubusercontent.com/20356276/121998378-14aec880-cdac-11eb-9cf8-fff74b54df8e.png">

2021-06-15 08:50 UTC, AMatutat commented
Funny, never saw something like this.

2021-06-15 10:00 UTC, Tobias321 commented
@cagix Is Fetch and merge wrong?

![image](https://user-images.githubusercontent.com/85501570/122033777-26569700-cdd1-11eb-81ce-afc628a69561.png)

2021-06-15 10:15 UTC, cagix commented
@Tobias321 updating your fork's `master` isn't the problem (except you introduced local changes to your `master`, that are not in upstream). that button should be just a shortcut for `git fetch upstream && git checkout master && git pull upstream master && git push origin master`... the point above was merging the upstream `master` into a (local) feature branch, which is considered bad practice :)

2021-06-15 10:34 UTC, Tobias321 commented
thanks, now i understand it. yes, each feature in an own feature branch...