HUD implemment TextStage
AMatutat/pmdungeon pull request #52
Opened 2021-06-09 17:06 UTC by RipDip

fixes #33

2021-06-09 17:19 UTC, cagix commented
@AMatutat Like in #51, it seems to me, that @RipDip used  #48 as starting point, so you're seeing quite a lot changes. Once #48 will be merged, this PR (#52) should just have commit 5a31520  (2c10f28 is cancelled by 1fa52fc) ... 

**I.e. we have now unfortunately introduced a dependency for merging: first #48 needs to be merged, then (after rebasing) #52 can be merged ...**

2021-06-09 17:48 UTC, RipDip commented
@AMatutat do we really needs TextStage/removeText, because with labalName.remove() the label is also removed?

2021-06-09 18:25 UTC, AMatutat requested changes
- Can you use #54  for code style? 
- And update the readme example

2021-06-09 19:35 UTC, cagix commented
@RipDip your changes to `.gitattributes` are in conflict w/ `master` ...

2021-06-09 23:14 UTC, AMatutat approved these changes
LGMT.

*NOTE: DONT MERGE! We have to fix this gradle sh** first*

2021-06-12 17:24 UTC, cagix commented
@RipDip @AMatutat the conflict (`.gitattributes`) will vanish once we have merged #48 and rebased this branch/pr ...

2021-06-12 17:41 UTC, cagix requested changes
Please rebase your branch on top of the current `master`, activate the editor plugin of your IDE and reformat your code ...

2021-06-12 17:41 UTC, cagix commented on .gitattributes
> +*.bat           text eol=crlf
@RipDip @AMatutat this will vanish once we have merged #48 and rebased this branch/pr ...

2021-06-12 17:41 UTC, cagix commented on core/src/de/fhbielefeld/pmdungeon/vorgaben/game/Controller/MainController.java
> +        //textHUD.draw();
why is this line commented out and not simply deleted?

2021-06-12 17:41 UTC, cagix commented on core/src/de/fhbielefeld/pmdungeon/vorgaben/graphic/HUD.java
> +        textHUD.removeText(label);
indentation? please use the editorconfig-plugin and reformat your code!

2021-06-13 09:03 UTC, cagix requested changes
thanks :)  this looks much better now, except for the line break on the long comments. could you please fix that?

2021-06-13 09:03 UTC, cagix commented on core/src/de/fhbielefeld/pmdungeon/vorgaben/game/Controller/MainController.java
> +                Constants.VIRTUALHEIGHT);
this could be a smell. would it be better to calculate the value before calling?

2021-06-13 11:26 UTC, cagix commented on core/src/de/fhbielefeld/pmdungeon/vorgaben/game/Controller/MainController.java
> +                Constants.VIRTUALHEIGHT);
@RipDip or even maybe

```java
camera = new DungeonCamera(null, 
                           Constants.VIRTUALHEIGHT * Constants.WIDTH / (float) Constants.HEIGHT,   
                           Constants.VIRTUALHEIGHT);
```

2021-06-13 11:28 UTC, cagix requested changes
looks better, thanks :)
now only the one bit with the constructor needs attention.

2021-06-14 16:04 UTC, AMatutat commented
- rebase
- merge class Hud and TextStage

2021-06-14 18:22 UTC, cagix commented
@RipDip There are some minor merge conflicts in `MainController.java`. Please choose the correct lines wisely ...

2021-06-15 10:33 UTC, RipDip commented
I have a problem with the rebase. I rebase my repo with the instruction https://gist.github.com/ravibhure/a7e0918ff4937c9ea1c456698dcd58aa
But I have to do a reverse, because one PR = 1 Issue and than the changes from Refactoring Packages are revert. I can do a revert from the old revert, but this is not beautiful.

2021-06-15 10:38 UTC, cagix commented
> I have a problem with the rebase.

@RipDip Yeah, there are so many merges in your history / branch, so rebasing is nearly impossible here ... Luckily, there are no merge conflicts, so we can just merge your feature branch as it is into `master` ...  :)

2021-06-15 10:42 UTC, cagix commented
in the feature we really should fully adopt the [github flow](https://docs.github.com/en/github/getting-started-with-github/quickstart/github-flow):

1. create feature branches off the current `master`
2. develop features independently
3. rebase feature branch on top of (then) current `master`
4. create pull request from feature branch into `master`, request at least two reviews
5. once there are at least two approvals (and no objections): merge

2021-06-15 10:51 UTC, RipDip commented
okay
sorry for the problem and the not beautiful PR
My repo have the changes from rebase now, so i can merge the class hud and TextStage.

2021-06-15 11:46 UTC, RipDip commented
I tested it with four labels, where by I can remove one and the other is still there or change the text of one label and the other labels keep the old text.

2021-06-17 14:12 UTC, AMatutat commented on desktop/src/de/pmdungeon/desktop/DesktopLauncher.java
> -    /**
@cagix  I thought this code style setup you did uses whitespaces. Am i wrong?

2021-06-17 14:21 UTC, cagix commented on desktop/src/de/pmdungeon/desktop/DesktopLauncher.java
> -    /**
> @cagix I thought this code style setup you did uses whitespaces. Am i wrong?

you are not wrong 😎  however, our developers need to install+activate the editorconfig plugin in their ide's ...

2021-06-17 14:39 UTC, AMatutat commented
Can confirm that it works. 
Also  tested it with some hudicons (pixelSystem and gridSystem).

2021-06-17 14:57 UTC, cagix requested changes
looks quite nice. however, i've got a couple of questions ... :)

2021-06-17 14:57 UTC, cagix commented on core/src/de/pmdungeon/graphic/HUD.java
> +        parameter.borderWidth = 1;
hmmm, is does this count as "magic number" already? should we add this to `constants`?

2021-06-17 14:57 UTC, cagix commented on core/src/de/pmdungeon/graphic/HUD.java
> +        BitmapFont font24 = generator.generateFont(parameter); // font size 24 pixels
this comment does worry me a wee bit. should we document this somewhere?

2021-06-17 14:57 UTC, cagix commented on core/src/de/pmdungeon/graphic/HUD.java
> +        labelStyle.font = font24;
do we need `font24` somewhere else? if not, this could be changed into `labelStyle.font = generator.generateFont(parameter);` ... ?

2021-06-17 14:57 UTC, cagix commented on core/src/de/pmdungeon/graphic/HUD.java
> +    public Label drawText(String text, String fontPath, Color color, int size, int width, int height, int x, int y) {
this methods looks like dark magic ... should there be a more explaining java doc?

2021-06-17 14:57 UTC, cagix commented on README.md
> +Damit wir unser Spiel auch richtig testen können, sollten wir unserem Helden noch die Möglichkeit zum Bewegen geben. Dafür fügen wir Steuerungsoptionen in der `Held.update`-Methode hinzu:
general style question: i would prefer to use `()` when referring to methods, i.e. `Held.update()` instead of `Held.update` ... this makes it easier for me to read the text and distinguish between fields and methods ... but there are also people who prefer it exactly the way it is written here ... 

@AMatutat what do you think?

2021-06-17 14:57 UTC, cagix commented on README.md
> +    //levelLabel.remove();
sometimes there is a blank between `//` and the text, sometimes not. i'd prefer the blank ;) 

@AMatutat whats your opinion?

2021-06-17 19:10 UTC, AMatutat commented on core/src/de/pmdungeon/graphic/HUD.java
> +        parameter.borderWidth = 1;
We could add another (default?) parameter `borderWidth` and do `parameter.borderWidth=borderWidth`.

2021-06-17 19:12 UTC, AMatutat commented on core/src/de/pmdungeon/graphic/HUD.java
> +        BitmapFont font24 = generator.generateFont(parameter); // font size 24 pixels
Actually, I'm not even sure this comment is correct, could be a left over of the tutorial I used. The font size should be `paramter.size`. Have to check that.

2021-06-17 19:16 UTC, AMatutat commented on README.md
> +Damit wir unser Spiel auch richtig testen können, sollten wir unserem Helden noch die Möglichkeit zum Bewegen geben. Dafür fügen wir Steuerungsoptionen in der `Held.update`-Methode hinzu:
Normally I use `Class.Method` and `Instanz.Method()` (or at least I try to be consistent in this)

2021-06-17 19:20 UTC, AMatutat commented on README.md
> +    //levelLabel.remove();
I'm pretty sure I don't have an opinion on that. 
But we should keep it consistence. 
#66

2021-06-17 19:20 UTC, AMatutat commented on README.md
> +Damit wir unser Spiel auch richtig testen können, sollten wir unserem Helden noch die Möglichkeit zum Bewegen geben. Dafür fügen wir Steuerungsoptionen in der `Held.update`-Methode hinzu:
#66

2021-06-17 19:25 UTC, AMatutat commented on core/src/de/pmdungeon/graphic/HUD.java
> +    public Label drawText(String text, String fontPath, Color color, int size, int width, int height, int x, int y) {
what exactly scares you?

2021-06-17 19:34 UTC, cagix commented on core/src/de/pmdungeon/graphic/HUD.java
> +        parameter.borderWidth = 1;
hmmm, you can better assess whether it's really worth it. (i'm fine with you just closing the comment with the reason "it's not worth it" ;)

2021-06-17 19:35 UTC, cagix commented on core/src/de/pmdungeon/graphic/HUD.java
> +    public Label drawText(String text, String fontPath, Color color, int size, int width, int height, int x, int y) {
well, i don't really understand the back and forth, i.e. why the objects are assembled the way they are here.

2021-06-17 19:36 UTC, cagix commented on README.md
> +Damit wir unser Spiel auch richtig testen können, sollten wir unserem Helden noch die Möglichkeit zum Bewegen geben. Dafür fügen wir Steuerungsoptionen in der `Held.update`-Methode hinzu:
ah, for `Class.Method` there is a notion like `Class#Method` ...

2021-06-17 19:38 UTC, cagix commented on README.md
> +    //levelLabel.remove();
proposal: intellij's auto-formatter would format this with spaces (`// comment`), so let's do it like this?

2021-06-17 19:41 UTC, AMatutat commented on README.md
> +    //levelLabel.remove();
if it makes you happy, we do it that way

2021-06-17 19:42 UTC, AMatutat commented on README.md
> +Damit wir unser Spiel auch richtig testen können, sollten wir unserem Helden noch die Möglichkeit zum Bewegen geben. Dafür fügen wir Steuerungsoptionen in der `Held.update`-Methode hinzu:
Yea right, how could i forgot that, anyway than we should do `Class#Method` and `Instance.Method()`

2021-06-17 19:43 UTC, cagix commented on README.md
> +    //levelLabel.remove();
happy is a pretty big term ;)  ... but since it would be reformatted with the auto-formatter later anyway, we might as well do it now, right?

2021-06-17 19:45 UTC, cagix commented on README.md
> +    //levelLabel.remove();
should we add a git-hook with an external formatter? then we would no longer be dependent on the various ide's and their formatters/styles ...

2021-06-17 19:50 UTC, AMatutat commented on core/src/de/pmdungeon/graphic/HUD.java
> +        parameter.borderWidth = 1;
I can see some use cases for that. So we add it. #67

2021-06-17 19:53 UTC, AMatutat commented on README.md
> +    //levelLabel.remove();
that would be cool

2021-06-17 20:04 UTC, AMatutat commented on core/src/de/pmdungeon/graphic/HUD.java
> +    public Label drawText(String text, String fontPath, Color color, int size, int width, int height, int x, int y) {
Yea this method needs a lot of "setup" Objects (`generator`, `parameter`, `labelStyle`) 
But I dont think any of this matters outside so a more explaining javadoc may be more confusing than helpfull.

2021-06-18 08:31 UTC, AMatutat commented on README.md
> +    //levelLabel.remove();
#68

2021-06-18 10:02 UTC, AMatutat commented
after the last changes are done, we can merge.

2021-06-20 09:47 UTC, AMatutat commented
argh because we merged #65 you have to rebase one more time

2021-06-20 10:56 UTC, RipDip commented
I think a rebase with 111 conflict is not so easily. I would create a new feature branch and add my changes and create a new Pull-Request. I think that is better.

2021-06-20 11:30 UTC, AMatutat commented
yea do that

2021-06-20 11:33 UTC, cagix commented
> I think a rebase with 111 conflict is not so easily. I would create a new feature branch and add my changes and create a new Pull-Request. I think that is better.

argl, this comes from #55 / #65 ... it's mostly deleted/moved files, but you'd be very careful to select the correct solution in each case. so, in the end in this case it might be easier to just push a new branch including your changes ... 

@AMatutat next time we really need to do either architectural changes first or last, but not in between ;)  (!set reminder to self)

2021-06-20 11:35 UTC, cagix commented
@RipDip seems, in github you can't change branches in an existing pr ... please refer in the new pr to this one and close this one for good.

2021-06-20 11:44 UTC, closed without merging

2021-06-20 11:50 UTC, cagix commented
@RipDip you have changed five files. with git diff you can find out the changes, but it is a bit more complicated here, because the paths of the files have changed in some cases. for example, you can do this for the class `HUD`: `git diff hud:core/src/de/pmdungeon/graphic/HUD.java master:src/de/pmdungeon/graphic/HUD.java`