Merge Sub-Projects
AMatutat/pmdungeon pull request #55
Opened 2021-06-12 14:28 UTC by Tobias321

implements #44

2021-06-12 15:16 UTC, Tobias321 commented
seems not to work (compiling is ok, but not gdx...)

before i can go on, we must close the Gradle and Maven PRs (#38, #39, #48) first

2021-06-12 15:40 UTC, cagix commented
> seems not to work (compiling is ok, but not gdx...)

yeah, i can imagine that requires quite some changes to `gradle.build` ...

> before i can go on, we must close the Gradle and Maven PRs (#38, #39, #48) first

that seems reasonable 😀

2021-06-12 17:27 UTC, cagix commented
@Tobias321 @AMatutat Perhaps we should postpone this PR for the time being. In #48 we change our Gradle configuration, which affects this PR. In #51 we change our packages, which affects this PR as well. ...

2021-06-12 17:55 UTC, cagix requested changes
There are some issues (see comments). However, we should really wait. #48 introduces changes to the Gradle config, and #51 will change the package structure. ...

2021-06-12 17:55 UTC, cagix commented on build.gradle
> +    // api "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
commented lines? can we delete this?

2021-06-12 17:55 UTC, cagix commented on build.gradle
> +            srcDirs 'src'
our folder layout is following the Gradle default layout, so this declaration shouldn't be needed ...

2021-06-12 17:55 UTC, cagix commented on build.gradle
> +// tag::wrapper[]
???

2021-06-12 17:55 UTC, cagix commented on build.gradle
>          maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
wasn't this already deleted in #48?

2021-06-12 17:55 UTC, cagix commented on build.gradle
> +// end::dependencies[]
???

2021-06-12 17:55 UTC, cagix commented on gradle.properties
> +systemProp.sonar.login=bcd0729a17b30afefc5736cee0805da641f2abd7
???

2021-06-12 17:55 UTC, cagix commented on settings.gradle
> +// include ''
???

2021-06-12 18:48 UTC, Tobias321 commented on build.gradle
> +    // api "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
yes

2021-06-12 18:49 UTC, Tobias321 commented on build.gradle
> +            srcDirs 'src'
i had troubles with Eclipse without these lines, even after a refresh, i don't know why

2021-06-12 18:51 UTC, Tobias321 commented on build.gradle
> +// tag::wrapper[]
not needed commented line

2021-06-12 18:54 UTC, Tobias321 commented on build.gradle
>          maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
in #48 `mavenLocal()` is still there

2021-06-12 18:55 UTC, Tobias321 commented on build.gradle
> +// end::dependencies[]
can go

2021-06-12 18:55 UTC, Tobias321 commented on settings.gradle
> +// include ''
can go

2021-06-12 18:57 UTC, Tobias321 commented on gradle.properties
> +systemProp.sonar.login=bcd0729a17b30afefc5736cee0805da641f2abd7
i don't know what that is

2021-06-12 19:08 UTC, Tobias321 commented
> Perhaps we should postpone this PR for the time being.

Good point, i agree.

2021-06-13 08:52 UTC, cagix commented on gradle.properties
> +systemProp.sonar.login=bcd0729a17b30afefc5736cee0805da641f2abd7
reference to sonarqube. should long be gone in #48 ...

2021-06-13 08:53 UTC, cagix commented on build.gradle
> +// end::dependencies[]
then let got ;)

2021-06-13 08:53 UTC, cagix commented on build.gradle
>          maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
yeah, but sonatype?

2021-06-13 08:53 UTC, cagix commented on build.gradle
> +// tag::wrapper[]
then let got ;)

2021-06-13 08:53 UTC, cagix commented on build.gradle
> +            srcDirs 'src'
strange ...

2021-06-13 08:54 UTC, cagix commented on build.gradle
> +    // api "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
then let got ;)

2021-06-13 08:55 UTC, cagix commented on settings.gradle
> +// include ''
then let go of it ... :)

2021-06-13 11:01 UTC, Tobias321 commented
I've tried to tidy up the gradle configuration files.

Now libgdx is starting pissing me off too.

The build and jar targets still works. But in the generated jar file libgdx is missing.

The `gradlew desktop:dist` target as described here https://github.com/libgdx/libgdx/wiki/Deploying-your-application no longer works, because we no longer split up the projects into core and desktop.

@cagix Please re-review the new commits.

2021-06-13 11:08 UTC, cagix commented
> Now libgdx is starting pissing me off too.

been there ... this version hell is just ... well, hell 😢

2021-06-13 11:13 UTC, cagix commented
> The build and jar targets still works. But in the generated jar file libgdx is missing.

@Tobias321 

i think we might not even need the jar in the future. currently, the students work with the jar file so that they don't have to deal with the code base divided into several projects. besides, the gradle configuration was rather difficult to understand before #48.

but next time they are supposed to work directly with the repo as a starting point. i.e. they only need the sources and a working gradle or maven.

2021-06-13 11:23 UTC, cagix requested changes
i feel that you have started from an old version of #48. some of the modifications there have not yet been taken into account here ...

2021-06-13 11:23 UTC, cagix commented on build.gradle
> +    jcenter()
jcenter() no longer exists. please remove this entry. 

this should have already been removed in #48. did you use an old version as a starting point?

2021-06-13 11:23 UTC, cagix commented on build.gradle
> +sourceCompatibility = 1.8
same here ... in #48 we use 1.11 ...

2021-06-13 11:23 UTC, cagix commented on build.gradle
> +    implementation 'com.google.code.gson:gson:2.8.6'
in #48 we had a separate definition for versions. perhaps this is not needed anymore. but it would be nice to handle all dependencies in an uniform way, i.e either use version numbers directly in all entries or use variables/properties in all entries. please don't mix :)

2021-06-13 11:23 UTC, cagix commented on build.gradle
> +            srcDirs 'src'
don't understand this. once you've setup an eclipse configuration via `gradlew eclipse` eclipse should understand the default folder layout?

2021-06-13 11:23 UTC, cagix commented on gradle.properties
> +version=1.0
please use @AMatutat 's current version (see "Releases")

2021-06-13 11:23 UTC, cagix commented on gradle.properties
> +aiVersion=1.8.0
hmmm, please use either properties/variables for all dependencies or for none ... (see my comment on `gradle.build`)

2021-06-13 11:23 UTC, cagix commented on build.gradle
> +targetCompatibility = 1.8
dito: 1.11

2021-06-13 11:58 UTC, Tobias321 commented
> this should have already been removed in #48. did you use an old version as a starting point?

😢 true. My branch is based on the current AMatutat:master 6a873fe , let my try to use your update_gradle def9e01 as base. But first, thanks for the re-review.

PS. should we merge our PRs by our own after a approval? i had did this with my fix first frame pr.

2021-06-13 12:21 UTC, cagix commented
> PS. should we merge our PRs by our own after a approval? i had did this with my fix first frame pr.

better leave the final merge to @AMatutat ... he is the master here ;)

2021-06-14 14:25 UTC, cagix requested changes
see comments :)

2021-06-14 14:25 UTC, cagix commented on build.gradle
> +apply plugin: "application"
i am not quite sure if you should or even could combine these plugins? i think we probably only need plugins `java` and `eclipse` here.

2021-06-14 14:25 UTC, cagix commented on build.gradle
> +    api group: 'com.google.code.gson', name: 'gson', version: '2.7'
still hard coded version numbers?

2021-06-14 14:25 UTC, cagix commented on build.gradle
> +    api "com.badlogicgames.gdx:gdx-ai:1.8.1"
the `api` keyword corresponds to the `java-library` plugin. you should probably use `implementation` instead ...

2021-06-14 14:42 UTC, Tobias321 commented on build.gradle
> +apply plugin: "application"
without `apply plugin: "java-library"` (and `api` later) the dependencies would not be in the jar. :( 

but right, some plugins are may not be needed.

2021-06-14 14:45 UTC, cagix commented on build.gradle
> +apply plugin: "application"
ah .. we really need to document this, at least as comment here ...

2021-06-14 18:17 UTC, cagix commented
@Tobias321 I'm afraid the Gradle configuration causes severe merge conflicts. Unfortunately, you started on an old version and then made your changes. ... I tried to do a rebase, but it's massive :/  Please be very careful, you can't just go ahead and accept "HEAD" or "Merge Sub-Projects", you need to look at each conflict carefully and pick up the right pieces from both every time ...

2021-06-14 19:29 UTC, Tobias321 commented
@cagix Thanks for the hint. :-)

2021-06-16 12:24 UTC, closed without merging