add Maven
AMatutat/pmdungeon pull request #58
Opened 2021-06-14 15:38 UTC by AMatutat

@all pls verify

2021-06-14 15:48 UTC, Kushurando approved these changes

2021-06-14 17:10 UTC, AMatutat commented
after second review please assign to me

2021-06-14 17:58 UTC, cagix commented
@AMatutat No need to rebase this branch. I tried it, but there are servere merge conflicts :-/  However, it affects just the maven config, so no need to rebase in the end :-)

2021-06-19 13:34 UTC, AMatutat commented
We merged #65 so i guess this need some adjustments. 

*Note: Next time we want to change the project structure, we should do it BEFORE we write build scripts*

2021-06-20 17:59 UTC, cagix requested changes
well, this needs to be rebased and reworked: we don't have `core` and `desktop` anymore ...

2021-06-20 17:59 UTC, cagix commented on .gitignore
> +## maven
now we have two maven sections? this one and another one below? please merge!

2021-06-20 17:59 UTC, cagix commented on README.md
> +Die erforderliche jar kann einfach über Maven erstellt werden. Hierfür kann der folgende Befehl genutzt werden:
s/jar/`jar`/

2021-06-20 17:59 UTC, cagix commented on README.md
> +    mvn package
remove indentation

2021-06-20 17:59 UTC, cagix commented on README.md
> +Die jar mit allen Abhängigkeiten inkludiert liegt nun unter *"desktop/target/pmdungeon-desktop-jar-with-dependencies.jar"* und kann nach belieben umbenannt werden.
jar => `jar`

*"desktop/target/pmdungeon-desktop-jar-with-dependencies.jar"* => "`desktop/target/pmdungeon-desktop-jar-with-dependencies.jar`"

2021-06-20 17:59 UTC, cagix commented on core/pom.xml
> +		<finalName>pmdungeon-core</finalName>
do we really have still `core`? iirc this got merged ...

2021-06-20 17:59 UTC, cagix commented on core/pom.xml
> +	<artifactId>core</artifactId>
do we really have still `core`? iirc this got merged ...

2021-06-20 17:59 UTC, cagix commented on desktop/pom.xml
> +	<artifactId>desktop</artifactId>
do we really have still `desktop`? iirc this got merged ...

2021-06-20 17:59 UTC, cagix commented on desktop/pom.xml
> +			<artifactId>core</artifactId>
do we really have still `core`? iirc this got merged ...

2021-06-20 17:59 UTC, cagix commented on desktop/pom.xml
> +		<finalName>pmdungeon-desktop</finalName>
do we really have still `desktop`? iirc this got merged ...

2021-06-20 17:59 UTC, cagix commented on pom.xml
> +
one blank line should suffice

2021-06-20 17:59 UTC, cagix commented on pom.xml
> +
one blank line should suffice

2021-06-20 17:59 UTC, cagix commented on pom.xml
> +</project>
no line ending here?

2021-06-20 18:15 UTC, Kushurando commented
I apparently can't revoke my approval from before, so don't count that for now, obviously

2021-06-20 19:31 UTC, Tobias321 requested changes
> $ git checkout upstream/Maven
> Note: switching to 'upstream/Maven'.
>
> You are in 'detached HEAD' state. 🙁 

There are some changes that needs to be in here. We don't longer have the split into core and desktop. Pls, update this PR and note cagix's review.

2021-06-21 15:47 UTC, AMatutat commented
#76

2021-06-21 15:47 UTC, closed without merging