Merge Sub-Projects 2
AMatutat/pmdungeon pull request #65
Opened 2021-06-16 12:26 UTC by Tobias321

resolves #44 

works fine for me :)

2021-06-16 14:58 UTC, cagix commented
is this the "clean" version of #55?

2021-06-16 16:06 UTC, cagix requested changes
had a quick look. overall: looks promising :)  however, there are quite a few wee questions ...

2021-06-16 16:06 UTC, cagix commented on build.gradle
> -        api "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-desktop"
in the old config we used `gdx-box2d-platform:$gdxVersion:natives-desktop`, whereas in the new config there is just `gdx-box2d:$gdxVersion`. is this by design?

2021-06-16 16:06 UTC, cagix commented on build.gradle
> -        api "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-desktop"
same as with `box2d-platform`

2021-06-16 16:06 UTC, cagix commented on build.gradle
> +    api group: 'com.google.code.gson', name: 'gson', version: '2.7'
also, in the old config we used a newer version: 2.8.6

2021-06-16 16:06 UTC, cagix commented on build.gradle
> -        api "com.badlogicgames.gdx:gdx:$gdxVersion"
this entry is missing in the new config. perhaps we don't need it, but it was generated by the libgdx-builder ...

2021-06-16 16:06 UTC, cagix commented on build.gradle
> +sourceSets {
still a bit puzzled why we'd need to declare this ...

2021-06-16 16:06 UTC, cagix commented on desktop/build.gradle
> -project.ext.mainClassName = "de.fhbielefeld.pmdungeon.desktop.DesktopLauncher"
shouldn't we declare something like this in the new config, too?

2021-06-16 16:06 UTC, cagix commented on desktop/build.gradle
> -task debug(dependsOn: classes, type: JavaExec) {
shouldn't we declare something like this in the new config, too?

2021-06-16 16:06 UTC, cagix commented on desktop/build.gradle
> -task dist(dependsOn: classes, type: Jar) {
shouldn't we declare something like this in the new config, too?

2021-06-16 16:51 UTC, Tobias321 commented
@cagix Thanks for the review. Please have a re-look on the new commits. Now we can add a main class and simply call `gradlew run`. (with no including in an IDE...) 🙂

2021-06-16 16:56 UTC, Tobias321 commented on build.gradle
> +    api group: 'com.google.code.gson', name: 'gson', version: '2.7'
this is just another (or a newer) syntax. i used the old one and a version number property now.

2021-06-16 17:05 UTC, cagix commented on build.gradle
> +    api group: 'com.google.code.gson', name: 'gson', version: '2.7'
yeah, we should either the newer or the older one, but should avoid mixing them ... :)

2021-06-16 17:07 UTC, cagix commented
> @cagix Thanks for the review. Please have a re-look on the new commits. Now we can add a main class and simply call `gradlew run`. (with no including in an IDE...) 🙂

so i can finally use my vim again? neat 😀 ... review needs some time, please hold the line ;) ...

2021-06-18 08:54 UTC, AMatutat approved these changes
Works for me. 
Question: All this gradle changes are not relevant for the subproject merge, right?

2021-06-18 09:13 UTC, Tobias321 commented
> All this gradle changes are not relevant for the subproject merge, right?

The gradle changes are relevant in this pr, because we don't have the projects core and desktop longer.

I tried to make as few changes as possible.

But if we merge this pr, the other pr may have to change...

2021-06-18 09:33 UTC, cagix requested changes
still one dependency missing which was originally in build.gradle ...

2021-06-18 09:33 UTC, cagix commented on build.gradle
> -        api "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-desktop"
still missing?

2021-06-18 09:33 UTC, cagix commented on build.gradle
> -        api "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-desktop"
done

2021-06-18 11:38 UTC, cagix requested changes
`Main` still here?

2021-06-18 11:38 UTC, cagix commented on src/de/pmdungeon/desktop/Main.java
> +public class Main extends MainController {
still here?

2021-06-18 11:53 UTC, Tobias321 commented on src/de/pmdungeon/desktop/Main.java
> +public class Main extends MainController {
sorry, my fault 😉

2021-06-18 12:16 UTC, Tobias321 commented on src/de/pmdungeon/desktop/Main.java
> +public class Main extends MainController {
@cagix i could rebase/squash/pick the branch, so that the Main.java commit is not to see in the history ...

2021-06-19 11:24 UTC, AMatutat commented
@cagix  @Tobias321 looks good now. Can i merge?

2021-06-19 12:56 UTC, Tobias321 commented
> @cagix  @Tobias321 looks good now. Can i merge? 

LGTM. I tested on Windows. You can merge.

2021-06-19 13:31 UTC, merged