added gradle documentation
AMatutat/pmdungeon pull request #72
Opened 2021-06-20 14:27 UTC by timonBusch

2021-06-20 17:50 UTC, cagix requested changes
nice text :)  had some questions and some remarks ...

2021-06-20 17:50 UTC, cagix commented on gradle_doc.md
> +## [Gradle](https://docs.gradle.org/current/userguide/userguide.html) Documentation
do not use links in headers ...

2021-06-20 17:50 UTC, cagix commented on gradle_doc.md
> +Gradle is an open-source build automation tool which runs on the JVM. The
this would be a better place for a link

2021-06-20 17:50 UTC, cagix commented on gradle_doc.md
> +Gradle uses a Wrapper, so the project can be build via `gradlew` or `gradlew.bat`.
s/Wrapper/wrapper/

"... can be ... `gradlew.bat`, which are included in the repository."

2021-06-20 17:50 UTC, cagix commented on gradle_doc.md
> +give a complete of all tasks. Run `gradlew <task>` to use a task.
"... a complete list of ..." (add "list")

2021-06-20 17:50 UTC, cagix commented on gradle_doc.md
> +
remove blank line

2021-06-20 17:50 UTC, cagix commented on gradle_doc.md
> +
remove blank line

2021-06-20 17:50 UTC, cagix commented on gradle_doc.md
> +To be able to compile Java for example the plugin `java` is
hmmm, something is missing, this sentence sounds not right ;)

proposal: "In order to be able to compile with Java, the `java` plugin was added to the project."

2021-06-20 17:50 UTC, cagix commented on gradle_doc.md
> +added to the project. The `java-library` plugin extends the java
s/extends the java/extends the `java`/

2021-06-20 17:50 UTC, cagix commented on gradle_doc.md
> +the `application` plugin will be also included.
s/will be also/has also been/

2021-06-20 17:50 UTC, cagix commented on gradle_doc.md
> +The Method that is used in this `build.gradle` is an older one
s/Method/method/ 

whats the take away of this sentence? we are using an older syntax? i'd remove this :)

2021-06-20 17:50 UTC, cagix commented on gradle_doc.md
> +Java plugin to define the Java version for the project.
s/Java/`java`/

2021-06-20 17:50 UTC, cagix commented on gradle_doc.md
> +A `sourceSet` represents a logical group of Java source and
Do we have a `sourceSet`? IIRC this was deleted since it was just standard?

2021-06-20 17:50 UTC, cagix commented on gradle_doc.md
> +needed in the project. The id which is written after the key
s/id/ID/ (?)

2021-06-20 17:50 UTC, cagix commented on gradle_doc.md
> +The `jar` task is implemented to create a Java Archive, so it can
s/Archive/archive/

2021-06-20 18:08 UTC, cagix commented
@timonBusch @AMatutat Shouldn't this file be in the new folder `docs/` and accessible (i.e. linked) via `README.md`?

2021-06-20 18:34 UTC, AMatutat commented
> Shouldn't this file be in the new folder docs/ and accessible (i.e. linked) via README.md?

guess we have two options
1. Move this file in the docs folder and link it in the readme
or
2. Write the content of this file in the readme itself. 

I prefer No. 1

2021-06-20 18:49 UTC, AMatutat requested changes

2021-06-20 18:49 UTC, AMatutat commented on gradle_doc.md
> +
can you add the yaml header?
```
title: "PM-Dungeon: Gradle"
author: "Timon Busch"
lang: en-EN
...
```

2021-06-21 11:47 UTC, cagix commented
@timonBusch @AMatutat There are several changed files that I did not expect to be changed in this PR, e.g. `docs/platform_DE.md`.... Is this intentional or does the feature branch need a proper rebasing?

2021-06-21 11:58 UTC, timonBusch commented on gradle_doc.md
> +A `sourceSet` represents a logical group of Java source and
https://github.com/AMatutat/pmdungeon/blob/961f0845f249c019bb655be4a721baa854863502/build.gradle#L8

here in our current build.gradle it is still i'm not so sure if we need or not

2021-06-28 08:25 UTC, cagix commented
@timonBusch Danke für den Beitrag. Hier sind wahnsinnig viele geänderte Dateien dabei, bist Du sicher, dass Dein Branch auf dem aktuellen `master`  aufsetzt? Bitte rebasen!

2021-06-28 08:43 UTC, timonBusch commented
Ich wollte auch eigentlich nur zwischendurch meinen Branch auf den neusten Stand bringen und haben deswegen den Master in meinen Feature branch gepullt mit rebase

2021-06-28 08:49 UTC, cagix commented
> Ich wollte auch eigentlich nur zwischendurch meinen Branch auf den neusten Stand bringen und haben deswegen den Master in meinen Feature branch gepullt mit rebase

ja, siehe meine ergänzungen zur letzten bemerken ... irgendwas übersehe ich?

2021-06-28 09:32 UTC, AMatutat commented
> Warum zeigt Github hier im PR dann 52(!) geänderte Dateien an?!!

Naja, GitHub sagt halt, meine Änderungen am Master sind auch Teil dieses PR. Weil GitHub....

@timonBusch Machen wirs einfach dirty aber einfach: Neuen Branch aus den Master ertellen, dein kram da nochmal manuell reinkopieren und dann neuer Merge Request..... Wenn GitHub nicht sauber arbeiten will, dann will ich auch nit mehr

2021-06-28 15:41 UTC, closed without merging