WIP: Add ant ivy scripts 2
AMatutat/pmdungeon pull request #73
Opened 2021-06-20 14:58 UTC by Tobias321

fixes #45, fixes #61 

this is still WIP

2021-06-20 18:06 UTC, cagix requested changes
looks promising 👍

2021-06-20 18:06 UTC, cagix commented on build.properties
> +gdxVersion=1.9.8
in maven (#58) this is `1.9.12`?

2021-06-20 18:06 UTC, cagix commented on build.xml
> +    <property name="ivy.install.version" value="2.1.0-rc2" />
could the ivy version be defined in `build.properties` as well?

2021-06-20 19:18 UTC, Tobias321 commented
i have added a ivyVersion property.

i don't understand, why now 8 files have changed. that wasn't an intention.

2021-06-21 14:11 UTC, Tobias321 commented
@cagix side note: you have to take care, i started the rebase via cmd... but solved the conflicts via github desktop. then i wanted to push via gd too, but github desktop then performs a "pull-push" (to avoid fast-forwarding, i assume...)

2021-06-21 14:54 UTC, cagix commented
> @cagix side note: you have to take care, i started the rebase via cmd... but solved the conflicts via github desktop. then i wanted to push via gd too, but github desktop then performs a "pull-push" (to avoid fast-forwarding, i assume...)

i really start to dislike this tool ...

2021-06-21 18:43 UTC, Tobias321 commented
have a look at `https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-platform/1.9.12/`
which of the listed dependencies could we need?
i tried it with "all":
```xml
    <dependencies>
        <dependency org="com.google.code.gson" name="gson" rev="${gsonVersion}" />
        <dependency org="com.badlogicgames.gdx" name="gdx-ai" rev="${gdxAiVersion}" />
        <dependency org="com.badlogicgames.gdx" name="gdx" rev="${gdxVersion}" />
        <dependency org="com.badlogicgames.gdx" name="gdx-backend-lwjgl" rev="${gdxVersion}" />
        <dependency org="com.badlogicgames.gdx" name="gdx-backend-lwjgl3" rev="${gdxVersion}" />
        <dependency org="com.badlogicgames.gdx" name="gdx-platform" rev="${gdxVersion}">
            <artifact name="gdx-platform" type="jar" />
            <artifact name="gdx-platform" type="jar" e:classifier="natives-desktop" />
            <artifact name="gdx-platform" type="jar" e:classifier="natives-x86" />
            <artifact name="gdx-platform" type="jar" e:classifier="natives-x86_64" />
            <artifact name="gdx-platform" type="jar" e:classifier="natives-arm64-v8a" />
            <artifact name="gdx-platform" type="jar" e:classifier="natives-ios" />
        </dependency>
        <dependency org="com.badlogicgames.gdx" name="gdx-box2d" rev="${gdxVersion}" />
        <dependency org="com.badlogicgames.gdx" name="gdx-box2d-platform" rev="${gdxVersion}">
            <artifact name="gdx-box2d-platform" type="jar" />
            <artifact name="gdx-box2d-platform" type="jar" e:classifier="natives-desktop" />
            <artifact name="gdx-box2d-platform" type="jar" e:classifier="natives-x86" />
            <artifact name="gdx-box2d-platform" type="jar" e:classifier="natives-x86_64" />
            <artifact name="gdx-box2d-platform" type="jar" e:classifier="natives-arm64-v8a" />
            <artifact name="gdx-box2d-platform" type="jar" e:classifier="natives-ios" />
        </dependency>
        <dependency org="com.badlogicgames.gdx" name="gdx-freetype" rev="${gdxVersion}" />
        <dependency org="com.badlogicgames.gdx" name="gdx-freetype-platform" rev="${gdxVersion}">
            <artifact name="gdx-freetype-platform" type="jar" />
            <artifact name="gdx-freetype-platform" type="jar" e:classifier="natives-desktop" />
            <artifact name="gdx-freetype-platform" type="jar" e:classifier="natives-x86" />
            <artifact name="gdx-freetype-platform" type="jar" e:classifier="natives-x86_64" />
            <artifact name="gdx-freetype-platform" type="jar" e:classifier="natives-arm64-v8a" />
            <artifact name="gdx-freetype-platform" type="jar" e:classifier="natives-ios" />
        </dependency>
        <dependency org="com.badlogicgames.gdx" name="gdx-tools" rev="${gdxVersion}" />
        <!-- <conflict manager="latest-compatible" /> -->
        <conflict manager="all" />
    </dependencies>
```
but there is still the same error, like there's still missing something, that ivy not but maven already retrieve.

2021-06-22 09:03 UTC, Tobias321 commented
works now 🙂 

i have compared the maven and ivy dependencies. we have to add lwjgl dependency, the natives for gdx-platform and to remove the gdx-tools dependency.

tested on windows x64. please test it too.

2021-06-22 12:04 UTC, AMatutat commented
still got
````
compile-run:
     [java] java.lang.NoClassDefFoundError: org/lwjgl/glfw/GLFWErrorCallbackI
```

2021-06-22 12:10 UTC, AMatutat commented
Now i get
```
compile-run:
     [java] [LWJGL] Failed to load a library. Possible solutions:
     [java]     a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
     [java]     b) Add the JAR that contains the shared library to the classpath.

```

2021-06-22 12:27 UTC, Tobias321 commented
@AMatutat can you show me the files of your `pmdungeon/lib` folder? are all natives, lwjgl and opengl jars in there?

or try to run with `-Djava.library.path="..."`

2021-06-22 12:30 UTC, AMatutat commented
![image](https://user-images.githubusercontent.com/32962412/122924762-6801b780-d366-11eb-8145-fd5191c92f45.png)

2021-06-22 12:35 UTC, Tobias321 commented
@AMatutat seems, natives-windows are missing at yours...

![image](https://user-images.githubusercontent.com/85501570/122925346-08f07280-d367-11eb-962f-428aecdba9a4.png)

2021-06-22 12:39 UTC, AMatutat commented
@Tobias321 but why?

2021-06-22 12:50 UTC, Tobias321 commented
> @Tobias321 but why?

i have deleted the `.ant`, `build`, `lib` and `libs` folders. then i have run `ant init-ivy` and `ant compile-run`

2021-06-22 13:32 UTC, Tobias321 commented
https://me.me/i/wait-see-what-i-found-in-this-room-free-him-c20e8e2b15c9402a83ae392624e4342b 😉

2021-06-22 14:13 UTC, AMatutat commented
> i have deleted the .ant, build, lib and libs folders. then i have run ant init-ivy and ant compile-run

works now. Guess my .ant is to blame.

2021-06-22 14:17 UTC, AMatutat requested changes

2021-06-22 14:17 UTC, AMatutat commented on README.md
> +- Run `ant init-ivy` once in your project folder, to initialize ivy, then use `ant compile-run` to compile your sources and to start the game.
something like "You have to add your main class in file blabala line x" is missing

2021-06-22 14:17 UTC, AMatutat commented on build.xml
> +        <!-- <ivy:retrieve pattern="${lib.dir}/[artifact]-[revision](-[classifier]).[ext]" /> -->
Can we delete that? I see no reason for commented out code.

2021-06-22 14:17 UTC, AMatutat commented on ivy.xml
> +        <!-- <conflict manager="latest-compatible" /> -->
Can we delete that? I see no reason for commented out code.

2021-06-22 14:17 UTC, AMatutat commented on ivysettings.xml
> +            <!-- <ibiblio name="my-jcenter" m2compatible="true" root="https://jcenter.bintray.com/" /> -->
Can we delete that? I see no reason for commented out code.

2021-06-22 14:17 UTC, AMatutat commented on README.md
> +- Run `ant init-ivy` once in your project folder, to initialize ivy, then use `ant compile-run` to compile your sources and to start the game.
oh and can we add a link to the Ant page?

2021-06-22 14:37 UTC, Tobias321 commented
> > i have deleted the .ant, build, lib and libs folders. then i have run ant init-ivy and ant compile-run
> 
> works now. Guess my .ant is to blame.

.ant is the cache folder for ant and ivy's home. sometimes is a good idea, to clear the (entire) cache.

2021-06-22 14:47 UTC, Tobias321 commented on README.md
> +- Run `ant init-ivy` once in your project folder, to initialize ivy, then use `ant compile-run` to compile your sources and to start the game.
done. but which link do you mean?

2021-06-22 14:59 UTC, AMatutat approved these changes

2021-06-22 15:28 UTC, merged