Docs (Eclipse integration)
AMatutat/pmdungeon pull request #85
Opened 2021-06-24 17:20 UTC by Tobias321

fixes #80 (Eclipse integration)

2021-06-25 08:33 UTC, AMatutat requested changes
looks good

2021-06-25 08:33 UTC, AMatutat commented on README.md
We should also add a "tutorial" for jar too.
Something linke:
Download the jar from Release (link) 
balbalbal

2021-06-25 08:33 UTC, AMatutat commented on README.md
> +- Use the delivered Gradle wrapper,
hmm, maybe:
"You don't need to install Gradle because you can use the delivered Gradle wrapper"

2021-06-25 08:33 UTC, AMatutat commented on README.md
> +- add or modify your main class in the `build.xml` file at line 17,
All bullet points should start with a capital letter

2021-06-25 09:47 UTC, Tobias321 commented
Thanks for review 👍🏻

2021-06-25 10:59 UTC, AMatutat approved these changes

2021-06-25 15:12 UTC, cagix requested changes
some minor improvements suggested

2021-06-25 15:12 UTC, cagix commented on README.md
> +- Add or modify your main class in the `build.xml` file at line 17
"Adapt settings in `build.xml` (property `...`) to reflect your main class."

line numbers tend to be quite volatile, better use names here.

2021-06-25 15:12 UTC, cagix commented on README.md
> +- Run `ant init-ivy` once in your project folder, to initialize ivy
isn't this a dependency to `ant run`?

2021-06-25 15:12 UTC, cagix commented on README.md
> +- Download and unzip Maven, set the Windows system path variables for Maven (see [here](https://maven.apache.org/install.html), set at least `MAVEN_HOME` and `%MAVEN_HOME%\bin`)
same here: there a students with linux or macos ...

2021-06-25 15:12 UTC, cagix commented on README.md
> +- Run `mvn clean compile` in your project folder, to compile your sources
-,

2021-06-25 15:12 UTC, cagix commented on README.md
> +- Use `mvn exec:java -Dexec.mainClass="de.pmdungeon.PACKAGE.MAIN"` to start the game
hint to adapt settings is missing (how to use own main class?)

2021-06-25 15:12 UTC, cagix commented on README.md
> +- Add or modify your main class in the `build.gradle` file at line 9
wouldn't use line numbers here as this could be quite volatile. better to point to a property or variable instead ...

2021-06-25 15:12 UTC, cagix commented on README.md
> +- Use `gradlew run` to start the game
wouldn't this also build (if necessary)?

2021-06-25 15:12 UTC, cagix commented on README.md
> +- Open Eclipse/your workspace
eclipse and workspace? eclipse or workspace?

2021-06-25 15:12 UTC, cagix commented on README.md
> +- You don't need to install Gradle because you can use the delivered Gradle wrapper
"... the Gradle wrapper provided in this project/repo."

2021-06-25 15:12 UTC, cagix commented on README.md
> +- Run `gradlew build` in your project folder, to compile your sources
-,

2021-06-25 15:12 UTC, cagix commented on README.md
> +- Choose the root directory and pick the `pom.xml`
what about ant or gradle?

2021-06-25 15:21 UTC, Tobias321 commented on README.md
> +- Choose the root directory and pick the `pom.xml`
Including an existing Ant or Gradle project works in a quite similar way. Let me do

2021-06-25 15:26 UTC, Tobias321 commented on README.md
> +- Choose the root directory and pick the `pom.xml`
But if we have three possible ways to including per IDE, this would be quick ~opaque

2021-06-25 16:29 UTC, Tobias321 commented
Thanks for your review 🙂 Please have a look again

2021-06-25 16:43 UTC, cagix requested changes
I would not give such detailed installation instructions for the different operating systems individually, but simply refer once (for all operating systems) to the respective Apache website. This is easier for us and we don't have to maintain these instructions. And we can't cover all variants of package managers anyway ...

2021-06-25 16:43 UTC, cagix commented on README.md
> +  - Run `sudo apt-get update` and then `sudo apt-get install ant`
technically this would apply to Debian'ish Linuxes only ... 

I'd simply just point to https://ant.apache.org/manual/install.html for the installation instructions.

2021-06-25 16:43 UTC, cagix commented on README.md
> +  - Run `sudo apt-get update` and then `sudo apt-get install maven`
same as above. just point to https://maven.apache.org/install.html to get instructions how to install this ...

2021-06-25 16:50 UTC, cagix commented on README.md
> +- Run `ant init-ivy` once in your project folder, to initialize ivy
Should we make `init-ivy` a dependency of `resolve`? And if so, would that work at all? Or do we need to restart Ant with the ivy jar in the classpath to load the ivy plugin? (So, if `resolve` would depend on `init-ivy`, could we just call `ant resolve` and it would download the plugin first and then resolve the dependencies?)

2021-06-25 16:52 UTC, cagix commented on README.md
> +- Run `mvn clean compile` in your project folder, to compile your sources
there is still a comma?

2021-06-25 16:54 UTC, cagix requested changes
still a typo ;)

2021-06-25 16:54 UTC, cagix commented on README.md
> +- Run `mvn clean compile` in your project folder, to clean old builds and to compile your sources
there is still a comma after "folder"?

2021-06-25 16:58 UTC, Tobias321 commented on README.md
> +- Run `mvn clean compile` in your project folder, to clean old builds and to compile your sources
👀

2021-06-26 09:24 UTC, Tobias321 commented on README.md
> +- Run `mvn clean compile` in your project folder, to clean old builds and to compile your sources
i don't have understand the syntax "-," 😉

2021-06-26 09:40 UTC, AMatutat commented on README.md
> +- Run `mvn clean compile` in your project folder, to clean old builds and to compile your sources
@cagix told you. nobody understand this....

2021-06-26 12:41 UTC, cagix approved these changes
👍

2021-06-26 14:20 UTC, merged