HUD.drawText parameter for borderWidth
AMatutat/pmdungeon pull request #86
Opened 2021-06-25 11:31 UTC by RipDip

fixes #67

2021-06-25 11:34 UTC, AMatutat requested changes

2021-06-25 11:34 UTC, AMatutat commented on src/de/pmdungeon/graphic/HUD.java
> +
copy javadoc from above without borderWidth

2021-06-25 14:53 UTC, cagix requested changes
see @AMatutat 's comment. would be nice, if you'd find a better solution to the many-parameters-method, but i can live with that.

2021-06-25 14:53 UTC, cagix commented on src/de/pmdungeon/graphic/HUD.java
> +  public Label drawText(String text, String fontPath, Color color, int size, int width, int height, int x, int y, int borderWidth) {
not happy w/ rather huge number of parameters, more than three are considered a smell ... but i guess, there is no simple refactoring here, right?

2021-06-25 14:53 UTC, cagix commented on src/de/pmdungeon/graphic/HUD.java
> +    FreeTypeFontGenerator.FreeTypeFontParameter parameter = new FreeTypeFontGenerator.FreeTypeFontParameter();
this is just one good reason to not like java 😈

2021-06-25 14:53 UTC, cagix commented on src/de/pmdungeon/graphic/HUD.java
> +
this.

2021-06-25 14:58 UTC, AMatutat commented on src/de/pmdungeon/graphic/HUD.java
> +  public Label drawText(String text, String fontPath, Color color, int size, int width, int height, int x, int y, int borderWidth) {
we could add more default options, like default color, size, width, height..... 
but to be honest, this would just limit the options.

2021-06-25 15:17 UTC, cagix commented on src/de/pmdungeon/graphic/HUD.java
> +  public Label drawText(String text, String fontPath, Color color, int size, int width, int height, int x, int y, int borderWidth) {
hmmm, perhaps some kind of dao could improve the situation. but i'm not sure either.

2021-06-28 09:35 UTC, AMatutat approved these changes

2021-06-28 09:37 UTC, AMatutat commented
i fixed the conflicts and added the javadoc.

2021-06-28 09:37 UTC, merged