Update README
AMatutat/pmdungeon pull request #90
Opened 2021-07-03 08:33 UTC by RipDip

Add IntelliJ IDEA integration and Mac OS

2021-07-03 15:06 UTC, cagix requested changes
👍some minor suggestions

2021-07-03 15:06 UTC, cagix commented on README.md
> +	- If no project is opened in IntelliJ IDEA, then Left click on `Open`. Otherwise Left click on `File` choose `Open`
"Left click" => "left click"

2021-07-03 15:06 UTC, cagix commented on README.md
> +- If you use Mac OS, you must add the VM-Argument `-XstartOnFirstThread`
is this specific to intellij? or is this generally required when using our dungeon on macos?

2021-07-03 22:56 UTC, AMatutat requested changes

2021-07-03 22:56 UTC, AMatutat commented on README.md
> +	- Choose `This Windows` or `new Windows`
realy WindowS?

2021-07-03 22:56 UTC, AMatutat commented on README.md
> +- If you use Mac OS, you must add the VM-Argument `-XstartOnFirstThread`
where to add this?

2021-07-04 08:51 UTC, cagix commented on README.md
> +- If you use Mac OS, you must add the VM-Argument `-XstartOnFirstThread`
not sure, maybe we introduce a "odds&ends" sections?

2021-07-04 13:46 UTC, cagix requested changes
🦖

2021-07-04 13:46 UTC, cagix commented on README.md
> +- If you use Mac OS, you must add the VM-Argument `-XstartOnFirstThread` in your IDE.
isn't the correct term "macOS"?

2021-07-04 13:46 UTC, cagix commented on README.md
> +		- By `VM options` you add `-XstartOnFirstThread`
"By" sounds kind of strange. Maybe "For" or "At"?

2021-07-04 13:46 UTC, cagix commented on README.md
> +		- By `Main Class` you add the main Class from the project root directory
dito

2021-07-04 13:46 UTC, cagix commented on README.md
> +	- In Eclipse:
"For" Eclipse?

2021-07-04 13:46 UTC, cagix commented on README.md
> +	- In IntelliJ IDEA
dito

2021-07-04 13:46 UTC, cagix commented on README.md
> +	- In IntelliJ IDEA
also: end line with ":"?

2021-07-04 16:35 UTC, cagix requested changes
one last "Mac OS" ... except this it looks fine to me.

2021-07-04 16:35 UTC, cagix commented on README.md
> +### Mac OS
still "Mac OS"? => "macOS" :)

2021-07-05 04:48 UTC, cagix reviewed
lgtm 👍

2021-07-05 09:25 UTC, AMatutat approved these changes

2021-07-05 09:25 UTC, merged